### ISSUE TITLE
自动申购报错

### ISSUE THREAD

**Issue by hardy110** [vex1023/vxTrader#4]
发现新的问题，自动申购报错，麻烦看下：
>>> trader.order_auto_ipo()
2017-06-02 18:22:39.778321 INFO trader.py [line:184] === Order auto IPO
2017-06-02 18:22:40.828455 INFO gfTrader.py [line:161] === Login success: xxxxxxxxxxx
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.5/site-packages/pandas/core/indexing.py", line 1434, in _has_valid_type
    error()
  File "/root/anaconda3/lib/python3.5/site-packages/pandas/core/indexing.py", line 1429, in error
    (key, self.obj._get_axis_name(axis)))
KeyError: 'the label [1] is not in the [index]'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda3/lib/python3.5/site-packages/vxTrader/trader.py", line 198, in order_auto_ipo
    lmt_buy = ipo_limit.loc[ipo_list.loc[symbol, 'exchange_type'], 'amount_limits']
  File "/root/anaconda3/lib/python3.5/site-packages/pandas/core/indexing.py", line 1325, in __getitem__
    return self._getitem_tuple(key)
  File "/root/anaconda3/lib/python3.5/site-packages/pandas/core/indexing.py", line 836, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "/root/anaconda3/lib/python3.5/site-packages/pandas/core/indexing.py", line 967, in _getitem_lowerdim
    section = self._getitem_axis(key, axis=i)
  File "/root/anaconda3/lib/python3.5/site-packages/pandas/core/indexing.py", line 1551, in _getitem_axis
    self._has_valid_type(key, axis)
  File "/root/anaconda3/lib/python3.5/site-packages/pandas/core/indexing.py", line 1442, in _has_valid_type
    error()
  File "/root/anaconda3/lib/python3.5/site-packages/pandas/core/indexing.py", line 1429, in error
    (key, self.obj._get_axis_name(axis)))
KeyError: 'the label [1] is not in the [index]'

**Comment by vex1023** [comment]
请用pip update -U vxTrader更新一下最新的版本。
